model: DeepSetModel
run_config:
  verbose: 2
  debug: True
  num_threads: 32

data: "train_data/"
labels:
  X_bbcc: [H_bb, H_cc]
  X_qq: [H_qq]
  background: [QCD_others]
columns: [0, 1, 2, 3, 4, 5, 6, 16, 17]
undersampling: #[300000, 10000]

pt_regress: True
hyperparameter_opt: False
adversarial: False

model_config:
  name: fatjet_md
  conv1d_layers: [64, 128, 256]
  classification_layers: [128, 64]
  regression_layers: [10]
  kernel_initializer: "lecun_uniform"
  aggregator: "mean"
  #beta: 1.1e-5

quantization_config:
  quantizer_bits: 9
  quantizer_bits_int: 2
  quantizer_alpha_val: 1
  pt_output_quantization: [16, 6]

training_config:
  weight_method: "none"
  reference: null
  epochs: 1000
  batch_size: 2048
  learning_rate: 0.01
  validation_split: 0.3

  loss_weights: [1., 1.0, 1.0]

  initial_sparsity: 0.0
  final_sparsity: 0.1

  EarlyStopping_patience: 15

  ReduceLROnPlateau_factor: 0.5
  ReduceLROnPlateau_patience: 7
  ReduceLROnPlateau_min_lr: 0.0000001

hls4ml_config:
  input_precision: "ap_fixed<16,6,AP_RND,AP_SAT>"
  class_precision: "ap_ufixed<16,6,AP_RND,AP_SAT>"
  reg_precision: "ap_fixed<16,6,AP_RND,AP_SAT>"

  project_name: "baseline"
