model: DeepSetModel
run_config:
  verbose: 2
  debug: True

data: "training_data/"
labels:
  background: [QCD_others]
  X_bbcc: [H_bb, H_cc]
  X_qq: [H_qq]
columns: #[0, 1, 2, 3, 4, 5, 6, 16, 17]
undersampling:

pt_regress: True
hyperparameter_opt: False
adversarial: False

model_config:
  name: fatjet_md
  conv1d_layers: [128, 256, 256]
  classification_layers: [256]
  regression_layers: [10]
  kernel_initializer: "lecun_uniform"
  aggregator: "mean"
  #beta: 1.1e-5

quantization_config:
  quantizer_bits: 16
  quantizer_bits_int: 2
  quantizer_alpha_val: 1
  pt_output_quantization: [16, 6]

training_config:
  weight_method: "mass"
  reference: "X_qq"
  epochs: 20
  batch_size: 256
  learning_rate: 0.001
  validation_split: 0.3

  loss_weights: [1., 1., 2.0]

  initial_sparsity: 0.0
  final_sparsity: 0.0

  EarlyStopping_patience: 10

  ReduceLROnPlateau_factor: 0.5
  ReduceLROnPlateau_patience: 5
  ReduceLROnPlateau_min_lr: 0.0000001

hls4ml_config:
  input_precision: "ap_fixed<24,12,AP_RND,AP_SAT>"
  class_precision: "ap_ufixed<24,12,AP_RND,AP_SAT>"
  reg_precision: "ap_fixed<16,6,AP_RND,AP_SAT>"

  project_name: "fatjet_md"
