include:
    - CI/cmssw.yml
    - template: Code-Quality.gitlab-ci.yml

stages:
  - data
  - train
  - evaluate
  - hls4ml
  - synth
  - emulate
  - emulation-evaluate
  - profile
  - reports
  - upload
  - test

variables:
    Name: new_samples_baseline_5param_extended_trk
    Inputs: baseline
    Model: baseline
    N_PARAMS: 5
    TRACK_ALGO: extended
    TRAIN: All200.root
    MINBIAS: MinBias_PU200.root
    BBBB: GluGluHHTo4B_PU200.root
    BBBB_EOS_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_jettuples_191125_151X/
    BBTT: GluGluHHTo2B2Tau_PU200.root
    BBTT_EOS_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_jettuples_191125_151X/
    VBFHTAUTAU: VBFHToTauTau_PU200.root
    NTUPLE_TREE: outnano/Jets
    SIGNAL: TT_PU200
    EOS_DATA_DIR: /eos/cms/store/cmst3/group/l1tr/sewuchte/l1teg/fp_jettuples_191125_151X/
    EOS_STORAGE_DIR: /eos/project/c/cms-l1t-jet-tagger/www/${CI_PROJECT_NAME}
    EOS_STORAGE_SUBDIR: branches/${CI_COMMIT_REF_SLUG}/${Name}/pipeline${CI_PIPELINE_ID}
    EOS_STORAGE_DATADIR: branches/${CI_COMMIT_REF_SLUG}/${Name}/TrainingFiles
    CMSSW_VERSION: 'CMSSW_15_1_0_pre4'
    CMSSW_L1CT: 'CMS-L1T-Jet-Tagging:L1PF_15_1_X_L1TSC4NGJetTagger'
    CMSSW_EMULATOR_WRAPPER: 'https://github.com/cms-hls4ml/L1TSC4NGJetModel.git'
    RERUN_ON_TAG: 'False'
    RUN_EMULATION: 'True'
    RUN_SYNTHESIS: 'True'
    TAG: 'v0.0.0'
    IMAGE: gitlab-registry.cern.ch/ml_l1/ops/docker-images/mamba_jettagger:latest

.template:
  image: $IMAGE
  before_script:
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
    - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
    - env
  script:
    - python $FOLDER/$SCRIPT $ARGS
  tags: 
    - cern-nextgen-h100
  # rules: # run automatically on default branch, tags, and on merge requests with 'ci::automatic-build' label; otherwise run manually
  #    - if: '($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_LABELS =~ /ci::automatic-build/)'
  #      when: on_success

data:
  extends:
    - .template
  stage: data
  tags: [cern-nextgen-highmem]
  variables:
    KUBERNETES_MEMORY_REQUEST: 128Gi
    KUBERNETES_CPU_REQUEST: 32
  rules:
    - changes:  # Include the job and set to when:manual if any of the follow paths match a modified file.
        - tagger/data/**
      when: manual
  script:
  - source activate tagger
  - mkdir data
  - cd data
  - export EOS_MGM_URL=root://eoscms.cern.ch
  - eos cp $EOS_DATA_DIR/${TRAIN} .
  - eos cp $EOS_DATA_DIR/${SIGNAL}.root .
  - cd ..
  - python tagger/data/make_data.py -i data/${TRAIN} --tree $NTUPLE_TREE -sig $SIGNAL
  - tar -cf training_data_$Inputs.tgz training_data
  - tar -cf signal_process_data.tgz signal_process_data
  - export EOS_MGM_URL=root://eosproject.cern.ch
  - eos mkdir -p ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}
  - eos cp training_data_$Inputs.tgz ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}
  - eos cp signal_process_data.tgz ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}

train:
  extends:
    - .template
  stage: train
  needs:
    - job : data
      optional: true
  script:
  - eos cp ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}/training_data_$Inputs.tgz .
  - tar -xf training_data_$Inputs.tgz
  - source activate tagger
  - ./CI/run_training.sh $RERUN_ON_TAG
  artifacts:
    paths:
      - output
    exclude:
      - .npy
    expire_in: 1 day

evaluate:
  extends:
    - .template
  stage: evaluate
  script:
  - nproc
  - eos cp ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}/training_data_$Inputs.tgz .
  - tar -xf training_data_$Inputs.tgz
  - source activate tagger
  - mkdir data
  - cd data
  - eos cp $EOS_DATA_DIR/$MINBIAS .
  - eos cp $BBBB_EOS_DIR/$BBBB .
  - eos cp $BBTT_EOS_DIR/$BBTT .
  - eos cp $EOS_DATA_DIR/$VBFHTAUTAU .
  - cd ..
  - echo "bbtt performance"
  - python tagger/plot/bbtt.py --deriveRate --minbias data/$MINBIAS -n 650000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/bbtt.py --deriveWPs --minbias data/$MINBIAS --signal data/$BBTT -n 650000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/bbtt.py --eff -s data/$BBTT -n 500000 --tree $NTUPLE_TREE -m output/$Model
  - echo "VBF tautau performance"
  - python tagger/plot/diTaus.py --deriveWPs --minbias data/$MINBIAS -n 650000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/diTaus.py --BkgRate --minbias data/$MINBIAS -n 500000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/diTaus.py --eff --vbf_sample data/$VBFHTAUTAU -n 500000 --tree $NTUPLE_TREE -m output/$Model
  - echo "Topology tautau performance"
  - python tagger/plot/diTaus_topo.py --deriveWPs --minbias data/$MINBIAS -n 1000000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/diTaus_topo.py --BkgRate --minbias data/$MINBIAS -n 1000000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/diTaus_topo.py --eff --vbf_sample data/$VBFHTAUTAU -n 1000000 --tree $NTUPLE_TREE -m output/$Model
  - echo "bbbb performance"
  - python tagger/plot/bbbb.py --deriveWPs --minbias data/$MINBIAS -n 650000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/bbbb.py --eff -s data/$BBBB -n 500000 --tree $NTUPLE_TREE -m output/$Model
  - echo "Single tau performance"
  - python tagger/plot/singleTau.py --deriveWPs --minbias data/$MINBIAS -n 1000000 --tree $NTUPLE_TREE -m output/$Model
  - python tagger/plot/singleTau.py --eff --vbf_sample data/$VBFHTAUTAU -n 1000000 --tree $NTUPLE_TREE -m output/$Model
  artifacts:
    paths:
      - output
    when: always
    exclude:
      - .npy
    expire_in: 7 days

hls4ml:
  tags: [k8s-eos]
  extends:
    - .template
  rules:
    - if: $RUN_SYNTHESIS == "True"
  stage: hls4ml
  needs:
    - job : train
      optional: true
  script:
  - eos cp ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}/training_data_$Inputs.tgz .
  - tar -xf training_data_$Inputs.tgz
  - source activate tagger
  - python tagger/firmware/hls4ml_convert.py -m output/$Model -o output/$Model/firmware
  artifacts:
    paths:
      - output/$Model/firmware
    expire_in: 1 day

synth:
  tags: [cern-nextgen-highmem]
  image: registry.cern.ch/ci4fpga/vivado:2024.2
  stage: synth
  needs : [hls4ml]
  variables:
    KUBERNETES_MEMORY_REQUEST: 128Gi
    KUBERNETES_CPU_REQUEST: 32
  rules:
    - if: $RUN_SYNTHESIS == "True"
  script:
    - source /opt/Xilinx/Vitis_HLS/2024.2/settings64.sh
    - cd output/$Model/firmware/L1TSC4NGJetModel
    - vitis_hls -f build_prj.tcl
    - vivado -mode batch -source vivado_synth.tcl
    - cd ../../..
  artifacts:
    paths:
      - output/$Model/firmware/L1TSC4NGJetModel
    expire_in: 1 day

emulation-evaluate:
  extends:
    - .template
  stage: emulation-evaluate
  tags: [k8s-eos]
  rules:
    - if: ($RUN_EMULATION == "True") && ($RUN_SYNTHESIS == "True")
  needs: [emulate,train,hls4ml]
  dependencies: [emulate,train,hls4ml]
  script:
  - mkdir data
  - cd data
  - cp ../${CMSSW_VERSION}/src/FastPUPPI/NtupleProducer/python/jetTuple_${TRACK_ALGO}_${N_PARAMS}.root .
  - cd ..
  - source activate tagger
  - python tagger/plot/makeEmulationPlot.py -r True -i data/jetTuple_${TRACK_ALGO}_${N_PARAMS}.root -m output/$Model
  artifacts:
    paths:
      - output/$Model
    expire_in: 1 day

profile:
  extends:
    - .template
  stage: profile
  tags: [cern-nextgen-highmem]
  needs: [synth,train]
  dependencies: [synth,train]
  rules:
    - if: ($RUN_SYNTHESIS == "True")
  script:
  - source activate tagger
  - eos cp ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}/signal_process_data.tgz .
  - tar -xf signal_process_data.tgz
  - python tagger/firmware/hls4ml_profile.py -p True -d signal_process_data/TT_PU200  -m output/$Model -of output/$Model/firmware -o output/$Model/plots/profile
  artifacts:
    paths:
      - output/$Model
    expire_in: 1 day

upload_new_model:
  image: gitlab-registry.cern.ch/ml_l1/ops/docker-images/mamba_jettagger:latest
  stage: upload
  tags: [k8s-eos]
  rules:
    - if: $RERUN_ON_TAG == "False"
  needs:
    - job: train
      optional: false
    - job: evaluate
      optional: false
    - job: emulation-evaluate
      optional: true
    - job: emulate
      optional: true
    - job: hls4ml
      optional: true
    - job: profile
      optional: true
  before_script:
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
    - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
  script:
    - ./CI/upload_new_model.sh
  artifacts:
    paths:
      - $Name
    expire_in: 1 day


upload_tagged_model:
  image: gitlab-registry.cern.ch/ml_l1/ops/docker-images/mamba_jettagger:latest
  stage: upload
  tags: [k8s-eos]
  needs: [emulation-evaluate,hls4ml,train,evaluate,profile]
  dependencies: [emulation-evaluate,hls4ml,train,evaluate,profile]
  rules:
    - if: $RERUN_ON_TAG == "True"
  before_script:
    - export PYTHONPATH=/builds/ml_l1/TrainTagger:$PYTHONPATH
    - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
  script:
    - source activate tagger
    - mkdir -p ${EOS_STORAGE_DIR}/tags/${TAG}/test/firmware
    - mkdir -p ${EOS_STORAGE_DIR}/tags/${TAG}/test/plots
    - mkdir $Name
    - cd tagger/firmware
    - tar -cvf L1TSC4NGJetModel.tgz L1TSC4NGJetModel
    - cp -r L1TSC4NGJetModel.tgz ${EOS_STORAGE_DIR}/tags/${TAG}/test/firmware/
    - cd ../..
    - mkdir $Name/plots
    - mv output/$Model/plots/emulation $Name/plots
    - mv output/$Model/plots/profile $Name/plots
    - mv output/$Model/plots/training/ $Name/plots
    - mv output/$Model/plots/physics/ $Name/plots
    - cd ..
    - rm -rf php-plots
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cern.ch/cebrown/php-plots -b feature/update_extension_grouping
    - export PATH="${PATH}:/builds/ml_l1/php-plots/bin"
    - pb_copy_index.py TrainTagger/${Name} --recursive
    # - pb_copy_index.py ${EOS_STORAGE_DIR}/tags/${TAG}/test --recursive
    - cd TrainTagger/${Name}
    - pb_deploy_plots.py plots ${EOS_STORAGE_DIR}/tags/${TAG}/test/plots --recursive --extensions png,pdf
  artifacts:
    paths:
      - $Name
    expire_in: 1 day

code_quality:
   tags:
    - docker-privileged-xl
   artifacts:
    reports:
      codequality: gl-code-quality-report.json

pylint:
  stage: test
  image: python:3.7-slim
  before_script:
    - mkdir -p public/badges public/lint
    - echo undefined > public/badges/$CI_JOB_NAME.score
    - pip install pylint-gitlab
  script:
    - pylint --exit-zero --output-format=text $(find -type f -name "*.py" ! -path "**/.venv/**") | tee /tmp/pylint.txt
    - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > codeclimate.json
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > public/lint/index.html
  after_script:
    - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
  artifacts:
    paths:
      - public
    reports:
      codequality: codeclimate.json
    when: always
